#!/bin/csh
#
# LSF batch script to run an MPI application
#
#BSUB -P P64000101           # project code
#BSUB -W 0:10                # wall-clock time limit (hrs:mins)
#BSUB -n 1                   # number of MPI tasks in job         
#BSUB -R "span[ptile=16]"    # max MPI tasks per node
#BSUB -J run                 # job name
#BSUB -o run.%J.out          # output file name in which %J is replaced by the job ID
#BSUB -e run.%J.err          # error file name in which %J is replaced by the job ID
#BSUB -q caldera             # queue

limit stacksize unlimited
setenv LD_LIBRARY_PATH ${NETCDF}/lib:$LD_LIBRARY_PATH

mpirun.lsf ./test_model
